// Hand-written FirebaseOptions — generated by `flutterfire configure` would
// look identical, but we don't want to introduce that CLI dependency.
//
// Android reads its config from `android/app/google-services.json` via the
// Gradle plugin, so for Android we rely on `Firebase.initializeApp()` with
// no options. Web has no such mechanism — it needs the values inline.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAktd4ktbSTZt_9DCgXrwc8UrhiRRPnquI',
    authDomain: 'junto-a622c.firebaseapp.com',
    projectId: 'junto-a622c',
    storageBucket: 'junto-a622c.firebasestorage.app',
    messagingSenderId: '224137779408',
    appId: '1:224137779408:web:40ab4aac1f2918c5b2a6d5',
    measurementId: 'G-WR1Y4S2PN5',
  );

  /// Public VAPID key for Web Push — passed to `getToken(vapidKey: ...)`.
  /// Generated in Firebase Console → Cloud Messaging → Web Push certificates.
  static const String webPushVapidKey =
      'BDu_G6bLW-e1HrIVwC64YFJUbMo6RDb57xvyr25YN7pz8PmG921LTcL3FmO9kNgZNAfdcxND8kQ7o_F1Rhjb1io';
}
